# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: actionpresenter 0.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "actionpresenter"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Tobias Casper"]
  s.date = "2014-10-01"
  s.description = "A lightweight presenter implementation for Ruby on Rails."
  s.email = "tobias.casper@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/actionpresenter.rb"
  ]
  s.homepage = "http://github.com/tlux/actionpresenter"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "A lightweight presenter implementation for Ruby on Rails."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, ["~> 4"])
      s.add_runtime_dependency(%q<actionpack>, ["~> 4"])
      s.add_runtime_dependency(%q<actionview>, ["~> 4"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
    else
      s.add_dependency(%q<activesupport>, ["~> 4"])
      s.add_dependency(%q<actionpack>, ["~> 4"])
      s.add_dependency(%q<actionview>, ["~> 4"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    end
  else
    s.add_dependency(%q<activesupport>, ["~> 4"])
    s.add_dependency(%q<actionpack>, ["~> 4"])
    s.add_dependency(%q<actionview>, ["~> 4"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
  end
end

